import {t} from '@lingui/macro'
import {Trans} from '@lingui/react'
import Color from 'color'
import _ from 'lodash'
import React, {Fragment} from 'react'

import TimeLineChart from 'components/ui/TimeLineChart'
import ACTIONS from 'data/ACTIONS'
import JOBS from 'data/JOBS'
import STATUSES from 'data/STATUSES'
import {DamageEvent} from 'fflogs'
import Module, {dependency} from 'parser/core/Module'
import Combatants from 'parser/core/modules/Combatants'
import {SimpleStatistic, Statistics} from 'parser/core/modules/Statistics'

import styles from './DNCGauges.module.css'

// Dances take more than a GCD to apply, during which time party members will be generating esprit for you
// We'll need to multiply the amount generated by the VERY rough-estimate of how many GCDs passed while you were dancing
const ESPRIT_GENERATION_MULTIPLIERS = {
	[ACTIONS.CASCADE.id]: 1,
	[ACTIONS.REVERSE_CASCADE.id]: 1,
	[ACTIONS.FOUNTAIN.id]: 1,
	[ACTIONS.FOUNTAINFALL.id]: 1,
	[ACTIONS.WINDMILL.id]: 1,
	[ACTIONS.RISING_WINDMILL.id]: 1,
	[ACTIONS.BLADESHOWER.id]: 1,
	[ACTIONS.BLOODSHOWER.id]: 1,
	[ACTIONS.SABER_DANCE.id]: 1,
	[ACTIONS.STANDARD_FINISH.id]: 2,
	[ACTIONS.SINGLE_STANDARD_FINISH.id]: 2,
	[ACTIONS.DOUBLE_STANDARD_FINISH.id]: 2,
	[ACTIONS.TECHNICAL_FINISH.id]: 3,
	[ACTIONS.SINGLE_TECHNICAL_FINISH.id]: 3,
	[ACTIONS.DOUBLE_TECHNICAL_FINISH.id]: 3,
	[ACTIONS.TRIPLE_TECHNICAL_FINISH.id]: 3,
	[ACTIONS.QUADRUPLE_TECHNICAL_FINISH.id]: 3,
}

const STANDARD_FINISHES = [
	ACTIONS.STANDARD_FINISH.id,
	ACTIONS.SINGLE_STANDARD_FINISH.id,
	ACTIONS.DOUBLE_STANDARD_FINISH.id,
]

const TECHNICAL_FINISHES = [
	ACTIONS.TECHNICAL_FINISH.id,
	ACTIONS.SINGLE_TECHNICAL_FINISH.id,
	ACTIONS.DOUBLE_TECHNICAL_FINISH.id,
	ACTIONS.TRIPLE_TECHNICAL_FINISH.id,
	ACTIONS.QUADRUPLE_TECHNICAL_FINISH.id,
]

const FINISHES = [
	...STANDARD_FINISHES,
	...TECHNICAL_FINISHES,
]

const ESPRIT_GENERATION_AMOUNT = 10

const ESPRIT_RATE_SELF = 0.25
const ESPRIT_RATE_PARTY = 0.2

const MAX_ESPRIT = 100
const SABER_DANCE_COST = 50

export default class EspritGauge extends Module {
	static handle = 'espritgauge'
	static title = t('dnc.esprit-gauge.title')`Esprit Gauge`

	@dependency private combatants!: Combatants
	@dependency private statistics!: Statistics

	private potentialOvercap = 0
	private espritConsumed = 0
	private avgGenerated = 0
	private history: any[] = []
	private currentEsprit = 0

	protected init() {
		this.addHook('damage', {by: 'player'}, this.onDamage)
		this.addHook('cast', {by: 'player', abilityId: ACTIONS.SABER_DANCE.id}, this.onConsumeEsprit)
		this.addHook('death', {to: 'player'}, this.onDeath)
		this.addHook('complete', this.onComplete)
	}
	private onDamage(event: DamageEvent) {
		if (!ESPRIT_GENERATION_MULTIPLIERS[event.ability.guid] || event.amount === 0) {
			return
		}
		let generatedAmt = 0
		if (this.combatants.selected.hasStatus(STATUSES.TECHNICAL_FINISH.id)) {
			console.log('technical active')
			generatedAmt += ESPRIT_GENERATION_MULTIPLIERS[event.ability.guid] * ESPRIT_GENERATION_AMOUNT * ESPRIT_RATE_PARTY * (Object.keys(this.combatants.getEntities()).length-1)
			// Finishes aren't a weaponskill, so they don't generate esprit
			if (!FINISHES[event.ability.guid]) {
				generatedAmt += ESPRIT_GENERATION_MULTIPLIERS[event.ability.guid] * ESPRIT_GENERATION_AMOUNT * ESPRIT_RATE_SELF
			}
		} else if (this.combatants.selected.hasStatus(STATUSES.ESPRIT.id)) {
			console.log('esprit')
			generatedAmt += ESPRIT_GENERATION_MULTIPLIERS[event.ability.guid] * ESPRIT_GENERATION_AMOUNT * ESPRIT_RATE_SELF
			if (this.combatants.selected.hasStatus(STATUSES.CLOSED_POSITION.id)) {
				console.log('closed position')
				generatedAmt += ESPRIT_GENERATION_MULTIPLIERS[event.ability.guid] * ESPRIT_GENERATION_AMOUNT * ESPRIT_RATE_PARTY
			}
		}
		this.avgGenerated += generatedAmt
		console.log(generatedAmt)
		if (generatedAmt > 0) {
			this.setEsprit(this.currentEsprit + generatedAmt)
		}
	}
	private onConsumeEsprit() {
		this.espritConsumed++
		if (this.currentEsprit < SABER_DANCE_COST) {
			const prevHistory = this.history.pop()
			prevHistory.y = SABER_DANCE_COST
			this.history.push(prevHistory)
		}
		this.setEsprit(this.currentEsprit - SABER_DANCE_COST)
	}
	private onDeath() {
		this.setEsprit(0)
	}
	private setEsprit(value: number) {
		this.currentEsprit = _.clamp(value, 0, MAX_ESPRIT)
		this.potentialOvercap += Math.max(0, value - this.currentEsprit)
		const t = this.parser.currentTimestamp - this.parser.fight.start_time
		this.history.push({t, y: this.currentEsprit})
	}

	private onComplete() {
		this.statistics.add(new SimpleStatistic({
			title: 'Esprit Ratio',
			icon: ACTIONS.SABER_DANCE.icon,
			value: (this.avgGenerated/this.espritConsumed).toFixed(2),
		}))
	}

	output() {
		console.log(this.potentialOvercap/SABER_DANCE_COST)
		const dncColor = Color(JOBS.DANCER.colour)

		// tslint:disable:no-magic-numbers
		const data = {
			datasets: [{
				label: 'Esprit',
				data: this.history,
				steppedLine: true,
				backgroundColor: dncColor.fade(0.8),
				borderColor: dncColor.fade(0.5),
			}],
		}
		// tslint:enable:no-magic-numbers

		return <Fragment>
		<span className={styles.helpText}>
			<Trans id="dnc.esprit-gauge.graph.help-text">This graph is a rough estimate of esprit at best. It's not able to be definitive, but it can help you spot general trends.</Trans>
		</span>
			<TimeLineChart data={data} />
		</Fragment>
	}
}
